version: '3.8'

services:
  fastapi_service:
    build: .
    container_name: fastapi_service
    volumes:
      - .:/app
      - ./certs:/app/certs  # Montar certificados SSL
    ports:
      - "8000:8000"
      - "443:8000"  # Puerto HTTPS adicional
    environment:
      - PYTHONUNBUFFERED=1
    restart: always