version: '3.8'

services:
  fastapi_service:
    build: .
    container_name: fastapi_service
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always